import ./tensor/zero/19tensor
import ./tensor/zero/91tensor
import ./tensor/XYZ/smallxtensor
import ./tensor/XYZ/smallytensor
import ./tensor/XYZ/smallztensor
import ./tensor/XYZ/midxtensor
import ./tensor/XYZ/midytensor
import ./tensor/XYZ/midztensor
import ./tensor/XYZ/Bigxtensor
import ./tensor/XYZ/Bigytensor
import ./tensor/XYZ/Bigztensor
def fermatXYZ:
  '19tensor + 91tensor' = 'zerotensor'
  'BigXtensor + midxtensor + smallxtensor' = 'BigXtensor + midxtensor + smallxtensor' = 'BigZtensor + midztensor + smallztensor'
